const Types = {
    GET_ALL_POST: 'GET_ALL_POST',
    GET_POST_BY_ID: 'GET_POST_BY_ID',
    UPDATE_POST: 'UPDATE_POST',
    DELETE_POST: 'DELETE_POST',

    //clean-up actions
    CLEAN_UP_ALL_POSTS: 'CLEAN_UP_ALL_POSTS',
    CLEAN_UP_SELECTED_POST: 'CLEAN_UP_SELECTED_POST',

    //spinner controller 
    SPINNER_CONTROLLER: 'SPINNER_CONTROLLER'
}
export default Types